create or replace PACKAGE BODY PKG_ALF_UTILITIES AS

PROCEDURE SP_ALF_DDL IS
V_COUNT NUMBER;
BEGIN
    --CREATE ALFRESCO NUM_ARRAY TABLE
    SELECT COUNT(1) INTO V_COUNT FROM ALL_OBJECTS
    WHERE OBJECT_NAME='ALF_NUM_ARRAY'
    AND OBJECT_TYPE='TYPE';
    IF V_COUNT=0 THEN
        EXECUTE IMMEDIATE 'CREATE OR REPLACE EDITIONABLE TYPE ALF_NUM_ARRAY AS TABLE OF NUMBER';
        EXECUTE IMMEDIATE 'CREATE TABLE TBL_ALF_NUM_FILTER (SEQUENCE_NO NUMBER(38,0), FILTER_TYPE VARCHAR2(50 CHAR),FILTER_VALUES NUMBER)';
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_NUM_FILTER ON TBL_ALF_NUM_FILTER (SEQUENCE_NO)';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE  SEQ_ALF_NUM_FILTER MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL';    
    END IF;
	SELECT COUNT(1) INTO V_COUNT FROM ALL_OBJECTS
    WHERE OBJECT_NAME='TBL_MIGRATION_PROCESS_LOG'
    AND OBJECT_TYPE='TABLE';
    IF V_COUNT=0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE TBL_MIGRATION_PROCESS_LOG( MIGRATION_PROCESS_ID NUMBER(38,0) NOT NULL, OBJECT_NAME VARCHAR2(100 CHAR) NOT NULL, EXEC_START DATE DEFAULT SYSDATE, EXEC_END DATE DEFAULT SYSDATE, TABLE_NAME VARCHAR2(100 CHAR), REF_NAME VARCHAR2(100 CHAR), REF_ID NUMBER(38,0), PRE_MIG_COUNT NUMBER(38,0), POST_MIG_COUNT NUMBER(38,0), ERROR_CODE VARCHAR2(50 CHAR), ERROR_MSG VARCHAR2(4000 CHAR), ERROR_STACK VARCHAR2(4000 CHAR), CALL_STACK VARCHAR2(4000 CHAR), ERROR_BACKTRACE VARCHAR2(4000 CHAR), REMARKS VARCHAR2(500 CHAR) )';
        EXECUTE IMMEDIATE 'ALTER TABLE TBL_MIGRATION_PROCESS_LOG ADD CONSTRAINT TBL_MIGRATION_PROCESS_LOG_PK PRIMARY KEY (MIGRATION_PROCESS_ID)';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_MIGRATION_PROCESS_LOG MINVALUE 1 MAXVALUE 999999999999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE';        
    END IF;
--EXCEPTION WHEN OTHERS
--THEN dbms_output.put_line('DDL Proc Error Code-'||SUBSTR( DBMS_UTILITY.format_error_stack
                 --|| DBMS_UTILITY.format_error_backtrace, 1, 4000)|| 'Error Code :'|| SQLCODE); 
END ;
END PKG_ALF_UTILITIES;
/