CREATE OR REPLACE EDITIONABLE TYPE ALF_NUM_ARRAY AS TABLE OF NUMBER;
/
CREATE TABLE TBL_ALF_NUM_FILTER
   (    SEQUENCE_NO NUMBER(38,0), 
                             FILTER_TYPE VARCHAR2(50 CHAR),
                             FILTER_VALUES NUMBER
   );
 /  
CREATE INDEX IDX_NUM_FILTER ON TBL_ALF_NUM_FILTER (SEQUENCE_NO) ;
CREATE SEQUENCE  SEQ_ALF_NUM_FILTER MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;